---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  resource: "workflow-instance"
  version: "default"
  rules:
    - actions: ["start_workflow_instance", "read_workflow_instance", "suspend_workflow_instance", "terminate_workflow_instance"]
      roles: ["workflow-admin"]
      condition:
        match:
          expr: request.resource.attr.businessApp in request.principal.attr.businessApps
      effect: EFFECT_ALLOW

    - actions: ["start_workflow_instance", "read_workflow_instance"]
      roles: ["business-user", "process-user"]
      condition:
        match:
          expr: request.resource.attr.businessApp in request.principal.attr.businessApps
      effect: EFFECT_ALLOW

    - actions: ["read_workflow_instance"]
      roles: ["viewer"]
      condition:
        match:
          expr: request.resource.attr.businessApp in request.principal.attr.businessApps
      effect: EFFECT_ALLOW