---
server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"
  logRequestPayloads: true

engine:
  defaultPolicyVersion: "default"

auxData:
  jwt:
    disableVerification: true

storage:
  driver: "disk"
  disk:
    directory: "tmp/cerbos/policies"
    watchForChanges: true

